[Desktop Entry]
Encoding=UTF-8
Name=Homerun Kicker
Name[de]=Homerun-Kicker
Name[el]=Homerun Kicker
Name[fi]=Homerun Kicker
Name[nl]=Programmastarter Homerun
Name[pt]=Homerun Kicker
Name[pt_BR]=Homerun Kicker
Name[sl]=Majhen zaganjalnik Homerun
Name[sv]=Homerun startprogram
Name[uk]=Меню Homerun
Name[x-test]=xxHomerun Kickerxx
Comment=Non-fullscreen version of Homerun
Comment[de]=Nicht-Vollbildversion von Homerun
Comment[el]=Έκδοση του Homerun χωρίς πλήρη οθόνη
Comment[fi]=Homerunin versio, joka ei vie koko näyttöä
Comment[nl]=Versie van Homerun zonder volledig scherm
Comment[pt]=Versão em ecrã não-completo do Homerun
Comment[pt_BR]=Versão do Homerun em janela
Comment[sl]=Različica Homeruna, ki ni celozaslonska
Comment[sv]=Version av Homerun utan fullskärmsläge
Comment[uk]=Неповноекранна версія Homerun
Comment[x-test]=xxNon-fullscreen version of Homerunxx

Icon=homerun
Type=Service
X-KDE-ServiceTypes=Plasma/Applet,Plasma/PopupApplet

X-Plasma-API=declarativeappletscript
X-Plasma-MainScript=ui/main.qml
X-KDE-PluginInfo-Author=Homerun Developers
X-KDE-PluginInfo-Name=org.kde.homerun-kicker
X-KDE-PluginInfo-Version=@HOMERUN_VERSION@
X-KDE-PluginInfo-Website=http://userbase.kde.org/Homerun
X-KDE-PluginInfo-Category=Application Launchers
X-KDE-PluginInfo-Depends=
X-KDE-PluginInfo-License=GPL v2+
X-KDE-PluginInfo-EnabledByDefault=true
